## generated by chatgpt
import socket


def udp_client(server_ip='127.0.0.1', server_port=8000):
    # 创建 UDP socket
    client_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

    try:
        while True:
            message = input("请输入要发送的消息（输入 'exit' 退出）：")
            if message.lower() == 'exit':
                print("退出客户端。")
                break

            # 发送消息到服务端
            client_socket.sendto(message.encode('utf-8'), (server_ip, server_port))

            # 接收来自服务端的响应
            data, addr = client_socket.recvfrom(1024)
            print(f"收到来自服务端 {addr} 的响应：{data.decode('utf-8')}")

    except KeyboardInterrupt:
        print("\n客户端中断退出。")

    finally:
        client_socket.close()


if __name__ == '__main__':
    udp_client()
